project:
  type: book
  output-dir: _book

book:
  title: "Installing the Countdown2030 RMNCAH Application"
  reader-mode: true
  
  page-footer: 
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://aphrcwaro.github.io/rmncah_guide/
  repo-url: https://github.com/aphrcwaro/cd2030.rmncah/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

format:
  html:
    theme: 
      - cosmo
      - cd2030.scss
    code-link: true
    
    author-meta: "David Kariuki"
    callout-appearance: simple

editor: visual

